server:
  port: 8899

spring:
  # thymeleaf start
  thymeleaf:
    prefix: classpath:/templates/html/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 开发时关闭缓存，不然没法看到实时页面
    cache: false
  # thymeleaf end
